# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a08d46f7d0382bb7ab869371249ecf29cfe43daa4d29a6e3dc59f08dbcd1f04eefbb2027e77a9bd9d742573f4b607b73ddd98aafa8d8843fc84b37cd1d0f6e

test:
  secret_key_base: c5753931bee6e8f5bb6299f982970a0aacf9ef66a38c4fb8686af8328a289ddb6a12be904ec1904d5259ff09b10827b37b28455542cac5cf5dc6e0bf92ae6002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
